### ISSUE TITLE
Reddit comments shown on Twitter posts 

### ISSUE THREAD

**Issue by random6969** [kogg/hovercards#246]
Example:

https://www.reddit.com/r/Android/comments/59l7t3/pixel_coming_to_tmobile_john_legere_hints_an/

When hovering over the post title, HoverCards correctly previews the Tweet. However, if I scroll down in the preview, I see Reddit comments rather than Twitter comments.

- chrome v54 on Windows 10

**Comment by saiichihashimoto** [comment]
This is because twitter doesn't have a replies API. In earlier versions of HoverCards, we would do a search on tweets in an attempt to find those replies. But this missed the correct tweets and produced the incorrect tweets far more often than actually showing the correct replies. Furthermore, twitter only lets you search the last 1% of tweets so improving our search won't do much. We decided to remove this functionality entirely since it wasn't actually providing any value.
